/* ###*B*###
 * Erika Enterprise, version 3
 * 
 * Copyright (C) 2018 Evidence s.r.l.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License, version 2, for more details.
 * 
 * You should have received a copy of the GNU General Public License,
 * version 2, along with this program; if not, see
 * <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html >.
 * 
 * This program is distributed to you subject to the following
 * clarifications and special exceptions to the GNU General Public
 * License, version 2.
 * 
 * THIRD PARTIES' MATERIALS
 * 
 * Certain materials included in this library are provided by third
 * parties under licenses other than the GNU General Public License. You
 * may only use, copy, link to, modify and redistribute this library
 * following the terms of license indicated below for third parties'
 * materials.
 * 
 * In case you make modified versions of this library which still include
 * said third parties' materials, you are obligated to grant this special
 * exception.
 * 
 * The complete list of Third party materials allowed with ERIKA
 * Enterprise version 3, together with the terms and conditions of each
 * license, is present in the file THIRDPARTY.TXT in the root of the
 * project.
 * ###*E*### */

/** \file	ee_dspic33ev_system.c
 *  \brief	DSPIC33_PIC24 System Initialization.
 *
 *  This files contains the sourcess of the System Initialization for Microchip
 *  dsPIC33EV Architecture available in Erika Enterprise.
 *
 *  \note	TO BE DOCUMENTED!!!
 *
 *  \author	Giuseppe Serano
 *  \date	2018
 */

/* ERIKA Enterprise Internals */
#include "ee_internal.h"

/*
 * System Initialization.
 */
FUNC(void, OS_CODE) osEE_dspic33_pic24_system_init(void)
{

#if	(!defined(OSEE_API_DYNAMIC))

#if	(								\
		defined(OSEE_DSPIC33_PIC24_OSCFAIL_ISR) &&		\
		(OSEE_DSPIC33_PIC24_OSCFAIL_ISR_CAT == 1)		\
)
	OSEE_DSPIC33_PIC24_OSCFAIL_ISR_CLR();
#endif	/* OSEE_DSPIC33_PIC24_OSCFAIL_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_ADDRERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_ADDRERR_ISR_CAT == 1)		\
)
	OSEE_DSPIC33_PIC24_ADDRERR_ISR_CLR();
#endif	/* OSEE_DSPIC33_PIC24_ADDRERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_STKERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_STKERR_ISR_CAT == 1)		\
)
	OSEE_DSPIC33_PIC24_STKERR_ISR_CLR();
#endif	/* OSEE_DSPIC33_PIC24_STKERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_MATHRERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_MATHERR_ISR_CAT == 1)		\
)
	OSEE_DSPIC33_PIC24_MATHERR_ISR_CLR();
#endif	/* OSEE_DSPIC33_PIC24_MATHERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_DMACERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_DMACERR_ISR_CAT == 1)		\
)
	OSEE_DSPIC33_PIC24_DMACERR_ISR_CLR();
#endif	/* OSEE_DSPIC33_PIC24_DMACERR_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_INT0_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_INT0_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_INT0_ISR) &&		\
			(OSEE_DSPIC33_PIC24_INT0_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_INT0_ISR_CLR();
	OSEE_DSPIC33_PIC24_INT0_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_INT0_ISR_PRI);
	OSEE_DSPIC33_PIC24_INT0_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_INT0_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_IC1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_IC1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_IC1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_IC1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_IC1_ISR_CLR();
	OSEE_DSPIC33_PIC24_IC1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_IC1_ISR_PRI);
	OSEE_DSPIC33_PIC24_IC1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_IC1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_OC1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_OC1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_OC1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_OC1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_OC1_ISR_CLR();
	OSEE_DSPIC33_PIC24_OC1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_OC1_ISR_PRI);
	OSEE_DSPIC33_PIC24_OC1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_OC1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_T1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_T1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_T1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_T1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_T1_ISR_CLR();
	OSEE_DSPIC33_PIC24_T1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_T1_ISR_PRI);
	OSEE_DSPIC33_PIC24_T1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_T1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_DMA0_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_DMA0_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_DMA0_ISR) &&		\
			(OSEE_DSPIC33_PIC24_DMA0_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_DMA0_ISR_CLR();
	OSEE_DSPIC33_PIC24_DMA0_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_DMA0_ISR_PRI);
	OSEE_DSPIC33_PIC24_DMA0_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_DMA0_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_IC2_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_IC2_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_IC2_ISR) &&		\
			(OSEE_DSPIC33_PIC24_IC2_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_IC2_ISR_CLR();
	OSEE_DSPIC33_PIC24_IC2_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_IC2_ISR_PRI);
	OSEE_DSPIC33_PIC24_IC2_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_IC2_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_OC2_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_OC2_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_OC2_ISR) &&		\
			(OSEE_DSPIC33_PIC24_OC2_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_OC2_ISR_CLR();
	OSEE_DSPIC33_PIC24_OC2_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_OC2_ISR_PRI);
	OSEE_DSPIC33_PIC24_OC2_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_OC2_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_T2_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_T2_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_T2_ISR) &&		\
			(OSEE_DSPIC33_PIC24_T2_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_T2_ISR_CLR();
	OSEE_DSPIC33_PIC24_T2_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_T2_ISR_PRI);
	OSEE_DSPIC33_PIC24_T2_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_T2_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_T3_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_T3_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_T3_ISR) &&		\
			(OSEE_DSPIC33_PIC24_T3_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_T3_ISR_CLR();
	OSEE_DSPIC33_PIC24_T3_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_T3_ISR_PRI);
	OSEE_DSPIC33_PIC24_T3_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_T3_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SPI1E_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SPI1E_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SPI1E_ISR) &&	\
			(OSEE_DSPIC33_PIC24_SPI1E_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_SPI1E_ISR_CLR();
	OSEE_DSPIC33_PIC24_SPI1E_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_SPI1E_ISR_PRI);
	OSEE_DSPIC33_PIC24_SPI1E_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SPI1E_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SPI1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SPI1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SPI1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_SPI1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_SPI1_ISR_CLR();
	OSEE_DSPIC33_PIC24_SPI1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_SPI1_ISR_PRI);
	OSEE_DSPIC33_PIC24_SPI1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SPI1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_U1RX_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_U1RX_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_U1RX_ISR) &&		\
			(OSEE_DSPIC33_PIC24_U1RX_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_U1RX_ISR_CLR();
	OSEE_DSPIC33_PIC24_U1RX_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_U1RX_ISR_PRI);
	OSEE_DSPIC33_PIC24_U1RX_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_U1RX_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_U1TX_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_U1TX_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_U1TX_ISR) &&		\
			(OSEE_DSPIC33_PIC24_U1TX_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_U1TX_ISR_CLR();
	OSEE_DSPIC33_PIC24_U1TX_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_U1TX_ISR_PRI);
	OSEE_DSPIC33_PIC24_U1TX_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_U1TX_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_AD1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_AD1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_AD1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_AD1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_AD1_ISR_CLR();
	OSEE_DSPIC33_PIC24_AD1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_AD1_ISR_PRI);
	OSEE_DSPIC33_PIC24_AD1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_AD1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_DMA1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_DMA1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_DMA1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_DMA1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_DMA1_ISR_CLR();
	OSEE_DSPIC33_PIC24_DMA1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_DMA1_ISR_PRI);
	OSEE_DSPIC33_PIC24_DMA1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_DMA1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_NVM_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_NVM_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_NVM_ISR) &&		\
			(OSEE_DSPIC33_PIC24_NVM_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_NVM_ISR_CLR();
	OSEE_DSPIC33_PIC24_NVM_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_NVM_ISR_PRI);
	OSEE_DSPIC33_PIC24_NVM_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_NVM_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SI2C1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SI2C1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SI2C1_ISR) &&	\
			(OSEE_DSPIC33_PIC24_SI2C1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_SI2C1_ISR_CLR();
	OSEE_DSPIC33_PIC24_SI2C1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_SI2C1_ISR_PRI);
	OSEE_DSPIC33_PIC24_SI2C1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SI2C1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_MI2C1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_MI2C1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_MI2C1_ISR) &&	\
			(OSEE_DSPIC33_PIC24_MI2C1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_MI2C1_ISR_CLR();
	OSEE_DSPIC33_PIC24_MI2C1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_MI2C1_ISR_PRI);
	OSEE_DSPIC33_PIC24_MI2C1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_MI2C1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_CMP1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_CMP1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_CMP1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_CMP1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_CMP1_ISR_CLR();
	OSEE_DSPIC33_PIC24_CMP1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_CMP1_ISR_PRI);
	OSEE_DSPIC33_PIC24_CMP1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_CMP1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_CN_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_CN_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_CN_ISR) &&		\
			(OSEE_DSPIC33_PIC24_CN_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_CN_ISR_CLR();
	OSEE_DSPIC33_PIC24_CN_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_CN_ISR_PRI);
	OSEE_DSPIC33_PIC24_CN_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_CN_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_INT1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_INT1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_INT1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_INT1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_INT1_ISR_CLR();
	OSEE_DSPIC33_PIC24_INT1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_INT1_ISR_PRI);
	OSEE_DSPIC33_PIC24_INT1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_INT1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_DMA2_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_DMA2_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_DMA2_ISR) &&		\
			(OSEE_DSPIC33_PIC24_DMA2_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_DMA2_ISR_CLR();
	OSEE_DSPIC33_PIC24_DMA2_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_DMA2_ISR_PRI);
	OSEE_DSPIC33_PIC24_DMA2_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_DMA2_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_OC3_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_OC3_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_OC3_ISR) &&		\
			(OSEE_DSPIC33_PIC24_OC3_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_OC3_ISR_CLR();
	OSEE_DSPIC33_PIC24_OC3_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_OC3_ISR_PRI);
	OSEE_DSPIC33_PIC24_OC3_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_OC3_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_OC4_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_OC4_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_OC4_ISR) &&		\
			(OSEE_DSPIC33_PIC24_OC4_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_OC4_ISR_CLR();
	OSEE_DSPIC33_PIC24_OC4_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_OC4_ISR_PRI);
	OSEE_DSPIC33_PIC24_OC4_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_OC4_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_T4_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_T4_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_T4_ISR) &&		\
			(OSEE_DSPIC33_PIC24_T4_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_T4_ISR_CLR();
	OSEE_DSPIC33_PIC24_T4_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_T4_ISR_PRI);
	OSEE_DSPIC33_PIC24_T4_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_T4_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_T5_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_T5_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_T5_ISR) &&		\
			(OSEE_DSPIC33_PIC24_T5_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_T5_ISR_CLR();
	OSEE_DSPIC33_PIC24_T5_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_T5_ISR_PRI);
	OSEE_DSPIC33_PIC24_T5_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_T5_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_INT2_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_INT2_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_INT2_ISR) &&		\
			(OSEE_DSPIC33_PIC24_INT2_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_INT2_ISR_CLR();
	OSEE_DSPIC33_PIC24_INT2_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_INT2_ISR_PRI);
	OSEE_DSPIC33_PIC24_INT2_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_INT2_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_U2RX_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_U2RX_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_U2RX_ISR) &&		\
			(OSEE_DSPIC33_PIC24_U2RX_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_U2RX_ISR_CLR();
	OSEE_DSPIC33_PIC24_U2RX_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_U2RX_ISR_PRI);
	OSEE_DSPIC33_PIC24_U2RX_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_U2RX_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_U2TX_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_U2TX_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_U2TX_ISR) &&		\
			(OSEE_DSPIC33_PIC24_U2TX_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_U2TX_ISR_CLR();
	OSEE_DSPIC33_PIC24_U2TX_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_U2TX_ISR_PRI);
	OSEE_DSPIC33_PIC24_U2TX_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_U2TX_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SPI2E_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SPI2E_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SPI2E_ISR) &&	\
			(OSEE_DSPIC33_PIC24_SPI2E_ISR_CAT == 1)		\
		  )						\
)
	OSEE_DSPIC33_PIC24_SPI2E_ISR_CLR();
	OSEE_DSPIC33_PIC24_SPI2E_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_SPI2E_ISR_PRI);
	OSEE_DSPIC33_PIC24_SPI2E_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SPI2E_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SPI2_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SPI2_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SPI2_ISR) &&		\
			(OSEE_DSPIC33_PIC24_SPI2_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_SPI2_ISR_CLR();
	OSEE_DSPIC33_PIC24_SPI2_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_SPI2_ISR_PRI);
	OSEE_DSPIC33_PIC24_SPI2_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SPI2_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_C1RX_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_C1RX_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_C1RX_ISR) &&		\
			(OSEE_DSPIC33_PIC24_C1RX_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_C1RX_ISR_CLR();
	OSEE_DSPIC33_PIC24_C1RX_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_C1RX_ISR_PRI);
	OSEE_DSPIC33_PIC24_C1RX_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_C1RX_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_C1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_C1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_C1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_C1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_C1_ISR_CLR();
	OSEE_DSPIC33_PIC24_C1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_C1_ISR_PRI);
	OSEE_DSPIC33_PIC24_C1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_C1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_DMA3_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_DMA3_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_DMA3_ISR) &&		\
			(OSEE_DSPIC33_PIC24_DMA3_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_DMA3_ISR_CLR();
	OSEE_DSPIC33_PIC24_DMA3_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_DMA3_ISR_PRI);
	OSEE_DSPIC33_PIC24_DMA3_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_DMA3_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_IC3_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_IC3_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_IC3_ISR) &&		\
			(OSEE_DSPIC33_PIC24_IC3_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_IC3_ISR_CLR();
	OSEE_DSPIC33_PIC24_IC3_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_IC3_ISR_PRI);
	OSEE_DSPIC33_PIC24_IC3_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_IC3_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_IC4_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_IC4_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_IC4_ISR) &&		\
			(OSEE_DSPIC33_PIC24_IC4_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_IC4_ISR_CLR();
	OSEE_DSPIC33_PIC24_IC4_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_IC4_ISR_PRI);
	OSEE_DSPIC33_PIC24_IC4_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_IC4_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_PSEM_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_PSEM_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_PSEM_ISR) &&		\
			(OSEE_DSPIC33_PIC24_PSEM_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_PSEM_ISR_CLR();
	OSEE_DSPIC33_PIC24_PSEM_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_PSEM_ISR_PRI);
	OSEE_DSPIC33_PIC24_PSEM_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_PSEM_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_U1E_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_U1E_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_U1E_ISR) &&		\
			(OSEE_DSPIC33_PIC24_U1E_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_U1E_ISR_CLR();
	OSEE_DSPIC33_PIC24_U1E_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_U1E_ISR_PRI);
	OSEE_DSPIC33_PIC24_U1E_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_U1E_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_U2E_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_U2E_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_U2E_ISR) &&		\
			(OSEE_DSPIC33_PIC24_U2E_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_U2E_ISR_CLR();
	OSEE_DSPIC33_PIC24_U2E_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_U2E_ISR_PRI);
	OSEE_DSPIC33_PIC24_U2E_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_U2E_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_C1TX_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_C1TX_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_C1TX_ISR) &&		\
			(OSEE_DSPIC33_PIC24_C1TX_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_C1TX_ISR_CLR();
	OSEE_DSPIC33_PIC24_C1TX_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_C1TX_ISR_PRI);
	OSEE_DSPIC33_PIC24_C1TX_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_C1TX_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_CTMU_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_CTMU_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_CTMU_ISR) &&		\
			(OSEE_DSPIC33_PIC24_CTMU_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_CTMU_ISR_CLR();
	OSEE_DSPIC33_PIC24_CTMU_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_CTMU_ISR_PRI);
	OSEE_DSPIC33_PIC24_CTMU_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_CTMU_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_PWM1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_PWM1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_PWM1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_PWM1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_PWM1_ISR_CLR();
	OSEE_DSPIC33_PIC24_PWM1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_PWM1_ISR_PRI);
	OSEE_DSPIC33_PIC24_PWM1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_PWM1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_PWM2_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_PWM2_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_PWM2_ISR) &&		\
			(OSEE_DSPIC33_PIC24_PWM2_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_PWM2_ISR_CLR();
	OSEE_DSPIC33_PIC24_PWM2_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_PWM2_ISR_PRI);
	OSEE_DSPIC33_PIC24_PWM2_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_PWM2_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_PWM3_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_PWM3_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_PWM3_ISR) &&		\
			(OSEE_DSPIC33_PIC24_PWM3_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_PWM3_ISR_CLR();
	OSEE_DSPIC33_PIC24_PWM3_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_PWM3_ISR_PRI);
	OSEE_DSPIC33_PIC24_PWM3_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_PWM3_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_ICD_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_ICD_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_ICD_ISR) &&		\
			(OSEE_DSPIC33_PIC24_ICD_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_ICD_ISR_CLR();
	OSEE_DSPIC33_PIC24_ICD_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_ICD_ISR_PRI);
	OSEE_DSPIC33_PIC24_ICD_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_ICD_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_I2C1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_I2C1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_I2C1_ISR) &&		\
			(OSEE_DSPIC33_PIC24_I2C1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_I2C1_ISR_CLR();
	OSEE_DSPIC33_PIC24_I2C1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_I2C1_ISR_PRI);
	OSEE_DSPIC33_PIC24_I2C1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_I2C1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_CAT == 2)	\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SENT1ERR_ISR) &&	\
			(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_CAT == 1)	\
		)							\
)
	OSEE_DSPIC33_PIC24_SENT1ERR_ISR_CLR();
	OSEE_DSPIC33_PIC24_SENT1ERR_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_PRI);
	OSEE_DSPIC33_PIC24_SENT1ERR_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SENT1ERR_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SENT1_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SENT1_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SENT1_ISR) &&	\
			(OSEE_DSPIC33_PIC24_SENT1_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_SENT1_ISR_CLR();
	OSEE_DSPIC33_PIC24_SENT1_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_SENT1_ISR_PRI);
	OSEE_DSPIC33_PIC24_SENT1_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SENT1_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SENT2ERR_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SENT2ERR_ISR_CAT == 2)	\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SENT2ERR_ISR) &&	\
			(OSEE_DSPIC33_PIC24_SENT2ERR_ISR_CAT == 1)	\
		)							\
)
	OSEE_DSPIC33_PIC24_SENT2ERR_ISR_CLR();
	OSEE_DSPIC33_PIC24_SENT2ERR_ISR_SET_PRIO(
		OSEE_DSPIC33_PIC24_SENT2ERR_ISR_PRI
	);
	OSEE_DSPIC33_PIC24_SENT2ERR_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SENT2ERR_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_SENT2_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_SENT2_ISR_CAT == 2)		\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_SENT2_ISR) &&	\
			(OSEE_DSPIC33_PIC24_SENT2_ISR_CAT == 1)		\
		)							\
)
	OSEE_DSPIC33_PIC24_SENT2_ISR_CLR();
	OSEE_DSPIC33_PIC24_SENT2_ISR_SET_PRIO(OSEE_DSPIC33_PIC24_SENT2_ISR_PRI);
	OSEE_DSPIC33_PIC24_SENT2_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_SENT2_ISR */

#if	(								\
		(							\
			defined(OSEE_DSPIC33_PIC24_ECCSBE_ISR_TID) &&	\
			(OSEE_DSPIC33_PIC24_ECCSBE_ISR_CAT == 2)	\
		) || (							\
			defined(OSEE_DSPIC33_PIC24_ECCSBE_ISR) &&	\
			(OSEE_DSPIC33_PIC24_ECCSBE_ISR_CAT == 1)	\
		)							\
)
	OSEE_DSPIC33_PIC24_ECCSBE_ISR_CLR();
	OSEE_DSPIC33_PIC24_ECCSBE_ISR_SET_PRIO(
		OSEE_DSPIC33_PIC24_ECCSBE_ISR_PRI
	);
	OSEE_DSPIC33_PIC24_ECCSBE_ISR_EN();
#endif	/* OSEE_DSPIC33_PIC24_ECCSBE_ISR */

#endif	/* !OSEE_API_DYNAMIC */

}	/* osEE_dspic33_pic24_system_init() */

/*
 * Interrupt Vector Table.
 */
#if	defined(OSEE_API_DYNAMIC)

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OscillatorFail)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OSCFAIL_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OSCFAIL_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_AddressError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ADDRERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_ADDRERR_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_HardTrapError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SGHT_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SGHT_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_StackError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_STKERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_STKERR_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_MathError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_MATHERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_MATHERR_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMACError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMACERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMACERR_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SoftTrapError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SGHT_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SGHT_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT0Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT0_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_INT0_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_IC1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OC1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA0Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA0_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMA0_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_IC2_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OC2_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T2_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T3_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI1ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI1E_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SPI1E_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SPI1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1RXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1RX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U1RX_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1TX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U1TX_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_AD1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_AD1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_AD1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMA1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_NVMInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_NVM_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_NVM_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SI2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SI2C1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SI2C1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_MI2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_MI2C1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_MI2C1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CMP1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CMP1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_CMP1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CNInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CN_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_CN_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_INT1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMA2_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OC3_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC4_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OC4_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T4_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T4_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T5Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T5_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T5_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_INT2_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2RXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2RX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U2RX_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2TX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U2TX_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI2ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI2E_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SPI2E_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SPI2_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1RxRdyInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1RX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_C1RX_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_C1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMA3_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_IC3_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC4_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_IC4_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWMSpEventMatchInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PSEM_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_PSEM_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1E_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U1E_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2E_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U2E_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1TX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_C1TX_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CTMUInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CTMU_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_CTMU_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_PWM1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_PWM2_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_PWM3_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_ICDInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ICD_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_ICD_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_I2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_I2C1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_I2C1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT1ERRInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT1ERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SENT1_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT2ERRInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT2ERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SENT2ERR_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SENT2_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_ECCSBEInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ECCSBE_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_ECCSBE_ISR_ID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#else	/* OSEE_API_DYNAMIC */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_OSCFAIL_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_OSCFAIL_ISR_CAT == 2)		\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OscillatorFail)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OSCFAIL_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OSCFAIL_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_OSCFAIL_ISR) &&		\
		(OSEE_DSPIC33_PIC24_OSCFAIL_ISR_CAT == 1)		\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_OSCFAIL_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OscillatorFail)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OSCFAIL_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_OSCFAIL_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_OscillatorFail)
#endif	/* OSEE_DSPIC33_PIC24_OSCFAIL_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_ADDRERR_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_ADDRERR_ISR_CAT == 2)		\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_AddressError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ADDRERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_ADDRERR_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_ADDRERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_ADDRERR_ISR_CAT == 1)		\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_ADDRERR_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_AddressError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ADDRERR_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_ADDRERR_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_AddressError)
#endif	/* OSEE_DSPIC33_PIC24_ADDRERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SGHT_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SGHT_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_HardTrapError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SGHT_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SGHT_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SGHT_ISR) &&			\
		(OSEE_DSPIC33_PIC24_SGHT_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SGHT_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_HardTrapError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SGHT_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SGHT_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_HardTrapError)
#endif	/* OSEE_DSPIC33_PIC24_SGHT_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_STKERR_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_STKERR_ISR_CAT == 2)		\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_StackError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_STKERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_STKERR_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_STKERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_STKERR_ISR_CAT == 1)		\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_STKERR_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_StackError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_STKERR_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_STKERR_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_StackError)
#endif	/* OSEE_DSPIC33_PIC24_STKERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_MATHERR_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_MATHERR_ISR_CAT == 2)		\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_MathError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_MATHERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_MATHERR_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_MATHERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_MATHERR_ISR_CAT == 1)		\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_MATHERR_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_MathError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_MATHERR_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_MATHERR_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_MathError)
#endif	/* OSEE_DSPIC33_PIC24_MATHERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_DMACERR_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_DMACERR_ISR_CAT == 2)		\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMACError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMACERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMACERR_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_DMACERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_DMACERR_ISR_CAT == 1)		\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_DMACERR_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMACError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMACERR_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_DMACERR_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_DMACError)
#endif	/* OSEE_DSPIC33_PIC24_DMACEERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SGST_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SGST_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SoftTrapError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	/* OSEE_DSPIC33_PIC24_SGST_ISR_CLR(); */
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SGST_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SGST_ISR) &&			\
		(OSEE_DSPIC33_PIC24_SGST_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SGST_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SoftTrapError)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	/* OSEE_DSPIC33_PIC24_SGST_ISR_CLR(); */
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SGST_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SoftTrapError)
#endif	/* OSEE_DSPIC33_PIC24_SGST_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_INT0_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_INT0_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT0Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT0_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_INT0_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_INT0_ISR) &&			\
		(OSEE_DSPIC33_PIC24_INT0_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_INT0_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT0Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT0_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_INT0_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_INT0Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_INT0_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_IC1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_IC1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_IC1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_IC1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_IC1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_IC1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_IC1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_IC1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_IC1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_OC1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_OC1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OC1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_OC1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_OC1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_OC1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_OC1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_OC1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_OC1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_T1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_T1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_T1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_T1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_T1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_T1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_T1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_T1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_DMA0_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_DMA0_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA0Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA0_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMA0_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_DMA0_ISR) &&			\
		(OSEE_DSPIC33_PIC24_DMA0_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_DMA0_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA0Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA0_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_DMA0_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_DMA0Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_DMA0_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_IC2_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_IC2_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_IC2_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_IC2_ISR) &&			\
		(OSEE_DSPIC33_PIC24_IC2_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_IC2_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC2_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_IC2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_IC2Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_IC2_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_OC2_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_OC2_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OC2_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_OC2_ISR) &&			\
		(OSEE_DSPIC33_PIC24_OC2_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_OC2_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC2_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_OC2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_OC2Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_OC2_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_T2_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_T2_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T2_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_T2_ISR) &&			\
		(OSEE_DSPIC33_PIC24_T2_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_T2_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T2_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_T2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_T2Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_T2_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_T3_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_T3_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T3_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_T3_ISR) &&			\
		(OSEE_DSPIC33_PIC24_T3_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_T3_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T3_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_T3_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_T3Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_T3_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SPI1E_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SPI1E_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI1ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI1E_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SPI1E_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SPI1E_ISR) &&		\
		(OSEE_DSPIC33_PIC24_SPI1E_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SPI1E_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI1ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI1E_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SPI1E_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SPI1ErrInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_SPI1E_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SPI1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SPI1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SPI1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SPI1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_SPI1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SPI1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SPI1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SPI1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_SPI1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_U1RX_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_U1RX_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1RXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1RX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U1RX_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_U1RX_ISR) &&			\
		(OSEE_DSPIC33_PIC24_U1RX_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_U1RX_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1RXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1RX_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_U1RX_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_U1RXInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_U1RX_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_U1TX_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_U1TX_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1TX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U1TX_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_U1TX_ISR) &&			\
		(OSEE_DSPIC33_PIC24_U1TX_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_U1TX_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1TX_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_U1TX_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_U1TXInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_U1TX_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_AD1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_AD1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_AD1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_AD1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_AD1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_AD1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_AD1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_AD1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_AD1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_AD1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_AD1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_AD1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_AD1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_DMA1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_DMA1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMA1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_DMA1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_DMA1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_DMA1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_DMA1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_DMA1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_DMA1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_NVM_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_NVM_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_NVMInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_NVM_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_NVM_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_NVM_ISR) &&			\
		(OSEE_DSPIC33_PIC24_NVM_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_NVM_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_NVMInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_NVM_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_NVM_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_NVMInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_NVM_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SI2C1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SI2C1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SI2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SI2C1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SI2C1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SI2C1_ISR) &&		\
		(OSEE_DSPIC33_PIC24_SI2C1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SI2C1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SI2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SI2C1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SI2C1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SI2C1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_SI2C1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_MI2C1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_MI2C1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_MI2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_MI2C1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_MI2C1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_MI2C1_ISR) &&		\
		(OSEE_DSPIC33_PIC24_MI2C1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_MI2C1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_MI2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_MI2C1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_MI2C1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_MI2C1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_MI2C1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_CMP1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_CMP1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CMP1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CMP1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_CMP1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_CMP1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_CMP1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_CMP1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CMP1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CMP1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_CMP1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_CMP1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_CMP1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_CN_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_CN_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CNInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CN_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_CN_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_CN_ISR) &&			\
		(OSEE_DSPIC33_PIC24_CN_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_CN_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CNInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CN_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_CN_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_CNInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_CN_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_INT1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_INT1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_INT1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_INT1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_INT1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_INT1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_INT1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_INT1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_INT1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_DMA2_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_DMA2_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMA2_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_DMA2_ISR) &&			\
		(OSEE_DSPIC33_PIC24_DMA2_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_DMA2_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA2_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_DMA2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_DMA2Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_DMA2_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_OC3_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_OC3_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OC3_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_OC3_ISR) &&			\
		(OSEE_DSPIC33_PIC24_OC3_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_OC3_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC3_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_DMA2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_OC3Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_OC3_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_OC4_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_OC4_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC4_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_OC4_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_OC4_ISR) &&			\
		(OSEE_DSPIC33_PIC24_OC4_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_OC4_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_OC4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_OC4_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_OC4_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_OC4Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_OC4_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_T4_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_T4_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T4_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T4_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_T4_ISR) &&			\
		(OSEE_DSPIC33_PIC24_T4_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_T4_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T4_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_T4_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_T4Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_T4_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_T5_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_T5_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T5Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T5_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_T5_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_T5_ISR) &&			\
		(OSEE_DSPIC33_PIC24_T5_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_T5_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_T5Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_T5_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_T5_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_T5Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_T5_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_INT2_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_INT2_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_INT2_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_INT2_ISR) &&			\
		(OSEE_DSPIC33_PIC24_INT2_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_INT2_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_INT2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_INT2_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_INT2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_INT2Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_INT2_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_U2RX_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_U2RX_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2RXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2RX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U2RX_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_U2RX_ISR) &&			\
		(OSEE_DSPIC33_PIC24_U2RX_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_U2RX_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2RXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2RX_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_U2RX_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_U2RXInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_U2RX_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_U2TX_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_U2TX_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2TX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U2TX_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_U2TX_ISR) &&			\
		(OSEE_DSPIC33_PIC24_U2TX_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_U2TX_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2TX_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_U2TX_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_U2TXInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_U2TX_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SPI2E_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SPI2E_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI2ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI2E_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SPI2E_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SPI2E_ISR) &&		\
		(OSEE_DSPIC33_PIC24_SPI2E_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SPI2E_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI2ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI2E_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SPI2E_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SPI2ErrInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_SPI2E_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SPI2_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SPI2_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SPI2_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SPI2_ISR) &&			\
		(OSEE_DSPIC33_PIC24_SPI2_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SPI2_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SPI2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SPI2_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SPI2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SPI2Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_SPI2_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_C1RX_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_C1RX_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1RxRdyInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1RX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_C1RX_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_C1RX_ISR) &&			\
		(OSEE_DSPIC33_PIC24_C1RX_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_C1RX_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1RxRdyInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1RX_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_C1RX_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_C1RxRdyInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_C1RX_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_C1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_C1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_C1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_C1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_C1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_C1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_C1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_C1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_C1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_DMA3_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_DMA3_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_DMA3_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_DMA3_ISR) &&			\
		(OSEE_DSPIC33_PIC24_DMA3_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_DMA3_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_DMA3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_DMA3_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_DMA3_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_DMA3Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_DMA3_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_IC3_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_IC3_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_IC3_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_IC3_ISR) &&			\
		(OSEE_DSPIC33_PIC24_IC3_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_IC3_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC3_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_IC3_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_IC3Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_IC3_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_IC4_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_IC4_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC4_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_IC4_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_IC4_ISR) &&			\
		(OSEE_DSPIC33_PIC24_IC4_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_IC4_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_IC4Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_IC4_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_IC4_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_IC4Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_IC4_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_PSEM_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_PSEM_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWMSpEventMatchInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PSEM_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_PSEM_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_PSEM_ISR) &&			\
		(OSEE_DSPIC33_PIC24_PSEM_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_PSEM_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWMSpEventMatchInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PSEM_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_PSEM_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_PWMSpEventMatchInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_PSEM_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_U1E_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_U1E_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1E_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U1E_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_U1E_ISR) &&			\
		(OSEE_DSPIC33_PIC24_U1E_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_U1E_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U1ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U1E_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_U1E_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_U1ErrInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_U1E_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_U2E_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_U2E_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2E_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_U2E_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_U2E_ISR) &&			\
		(OSEE_DSPIC33_PIC24_U2E_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_U2E_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_U2ErrInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_U2E_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_U2E_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_U2ErrInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_U2E_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_C1TX_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_C1TX_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1TX_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_C1TX_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_C1TX_ISR) &&			\
		(OSEE_DSPIC33_PIC24_C1TX_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_C1TX_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_C1TXInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_C1TX_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_C1TX_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_C1TXInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_C1TX_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_CTMU_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_CTMU_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CTMUInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CTMU_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_CTMU_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_CTMU_ISR) &&			\
		(OSEE_DSPIC33_PIC24_CTMU_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_CTMU_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_CTMUInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_CTMU_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_CTMU_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_CTMUInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_CTMU_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_PWM1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_PWM1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_PWM1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_PWM1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_PWM1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_PWM1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_PWM1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_PWM1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_PWM1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_PWM2_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_PWM2_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_PWM2_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_PWM2_ISR) &&			\
		(OSEE_DSPIC33_PIC24_PWM2_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_PWM2_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM2_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_PWM2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_PWM2Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_PWM2_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_PWM3_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_PWM3_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM3_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_PWM3_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_PWM3_ISR) &&			\
		(OSEE_DSPIC33_PIC24_PWM3_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_PWM3_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_PWM3Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_PWM3_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_PWM3_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_PWM3Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_PWM3_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_ICD_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_ICD_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_ICDInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ICD_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_ICD_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_ICD_ISR) &&			\
		(OSEE_DSPIC33_PIC24_ICD_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_ICD_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_ICDInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ICD_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_ICD_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_ICDInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_ICD_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_I2C1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_I2C1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_I2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_I2C1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_I2C1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_I2C1_ISR) &&			\
		(OSEE_DSPIC33_PIC24_I2C1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_I2C1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_I2C1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_I2C1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_I2C1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_I2C1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_I2C1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_CAT == 2)		\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT1ERRInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT1ERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SENT1ERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_SENT1ERR_ISR_CAT == 1)		\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SENT1ERR_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT1ERRInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT1ERR_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SENT1ERR_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SENT1ERRInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_SENT1ERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SENT1_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SENT1_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT1_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SENT1_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SENT1_ISR) &&		\
		(OSEE_DSPIC33_PIC24_SENT1_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SENT1_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT1Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT1_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SENT1_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SENT1Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_SENT1_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SENT2ERR_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SENT2ERR_ISR_CAT == 2)		\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT2ERRInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT2ERR_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SENT2ERR_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SENT2ERR_ISR) &&		\
		(OSEE_DSPIC33_PIC24_SENT2ERR_ISR_CAT == 1)		\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SENT2ERR_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT2ERRInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT2ERR_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SENT2ERR_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SENT2ERRInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_SENT1ERR_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_SENT2_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_SENT2_ISR_CAT == 2)			\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT2_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_SENT2_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_SENT2_ISR) &&		\
		(OSEE_DSPIC33_PIC24_SENT2_ISR_CAT == 1)			\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_SENT2_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_SENT2Interrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_SENT2_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SENT2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_SENT2Interrupt)
#endif	/* OSEE_DSPIC33_PIC24_SENT2_ISR */

#if	(								\
		defined(OSEE_DSPIC33_PIC24_ECCSBE_ISR_TID) &&		\
		(OSEE_DSPIC33_PIC24_ECCSBE_ISR_CAT == 2)		\
)
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_ECCSBEInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ECCSBE_ISR_CLR();
	osEE_dspic33_pic24_isr2_stub(OSEE_DSPIC33_PIC24_ECCSBE_ISR_TID);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(								\
		defined(OSEE_DSPIC33_PIC24_ECCSBE_ISR) &&		\
		(OSEE_DSPIC33_PIC24_ECCSBE_ISR_CAT == 1)		\
)
extern FUNC(void, OS_CODE) OSEE_DSPIC33_PIC24_ECCSBE_ISR ( void );
FUNC(void, OS_CODE) OSEE_ISR_NO_AUTO_PSV (_ECCSBEInterrupt)(void)
{
	OSEE_DSPIC33_PIC24_ISR_PRESTUB();
	OSEE_DSPIC33_PIC24_ECCSBE_ISR_CLR();
	osEE_dspic33_pic24_isr1_stub(OSEE_DSPIC33_PIC24_SENT2_ISR);
	OSEE_DSPIC33_PIC24_ISR_POSTSTUB();
}

#elif	(defined(OSEE_MCU_EXTENDED_STATUS))
OSEE_DSPIC33_PIC24_ISR_NOT_DEFINED(_ECCSBEInterrupt)
#endif	/* OSEE_DSPIC33_PIC24_ECCSBE_ISR */

#endif	/* OSEE_API_DYNAMIC */
